####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

# https://home-assistant.io/docs/ha_configuration/basic/

homeassistant:
  packages: !include_dir_named packages/
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 194
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include ha_configuration/customize.yaml
  auth_providers:
   - type: homeassistant

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################


# https://home-assistant.io/components/config/
config:
# https://home-assistant.io/components/sun/
sun:
# https://home-assistant.io/components/http/
http:
# https://home-assistant.io/components/updater/
updater:
# https://home-assistant.io/components/discovery/
discovery:
# https://home-assistant.io/components/conversation/
conversation:
# https://home-assistant.io/components/recorder/
recorder: !include ha_configuration/recorder.yaml
# https://home-assistant.io/components/history/
history:
# https://home-assistant.io/components/tts/
tts:
 - platform: google_translate
   cache: true
   cache_dir: /tts
   time_memory: 300
   base_url: http://192.168.178.203:8123
   language: 'de'
# https://home-assistant.io/components/python_script/
python_script:
# https://www.home-assistant.io/docs/mqtt/broker#embedded-broker
mqtt:
  broker: 192.168.178.3
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pw
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
# https://www.home-assistant.io/components/system_health/
system_health:
# https://www.home-assistant.io/components/person/
person:
# https://www.home-assistant.io/integrations/logger
logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

# https://home-assistant.io/docs/ha_configuration/splitting_ha_configuration/

group: !include ha_configuration/groups.yaml
#automation: !include_dir_merge_list ha_automations/
automation: !include automations.yaml
script: !include_dir_merge_named ha_scripts/
device_tracker: !include ha_configuration/device_tracker.yaml
notify: !include ha_configuration/notification.yaml
switch: !include ha_configuration/switches.yaml
climate: !include ha_configuration/climate.yaml
sensor: !include ha_configuration/sensors.yaml
shell_command: !include ha_configuration/shell_commands.yaml
logbook: !include ha_configuration/logbook.yaml
light: !include ha_configuration/lights.yaml
zone: !include ha_configuration/zones.yaml
camera: !include ha_configuration/camera.yaml
media_player: !include ha_configuration/media_player.yaml
input_boolean: !include ha_configuration/input_boolean.yaml
input_select: !include ha_configuration/input_select.yaml
input_text: !include ha_configuration/input_text.yaml
google_assistant: !include ha_configuration/google_assistant.yaml
binary_sensor: !include ha_configuration/binary_sensor.yaml

####################################################
#                                                  #
#                PANEL IFRAME                      #
#                                                  #
####################################################

# https://www.home-assistant.io/components/panel_iframe/

panel_iframe:
  grafana:
    title: 'Grafana'
    icon: mdi:graphql
    url: !secret grafana_iframe
  traefik:
    title: 'Traefik'
    icon: mdi:ip-network
    url: !secret traefik_iframe
  portainer:
    title: 'Portainer'
    icon: mdi:docker
    url: !secret portainer_iframe

####################################################
#                                                  #
#                  FRITZ HOME                      #
#                                                  #
####################################################

# https://github.com/hthiery/homeassistant

#fritzbox:
#  devices:
#    - host: 192.168.178.1
#      username: !secret fritzbox_username
#      password: !secret fritzbox_password

####################################################
#                                                  #
#                  GOOGLE CALENDAR                 #
#                                                  #
####################################################

# https://www.home-assistant.io/components/calendar.google/

google:
  client_id: !secret gcalendar_client_id
  client_secret: !secret gcalendar_client_secret

####################################################
#                                                  #
#                      SONOS                       #
#                                                  #
####################################################

# https://home-assistant.io/components/media_player.sonos/

sonos:
  media_player:
    hosts:
      - 192.168.178.10
      - 192.168.178.11
      - 192.168.178.12
      - 192.168.178.13
      - 192.168.178.14

####################################################
#                                                  #
#                       WOL                        #
#                                                  #
####################################################

# https://www.home-assistant.io/integrations/wake_on_lan

wake_on_lan:

####################################################
#                                                  #
#                   CHROMECAST                     #
#                                                  #
####################################################

# https://home-assistant.io/components/media_player.cast/

cast:
  media_player:
  - host: 192.168.178.9

####################################################
#                                                  #
#                    SPEEDTEST                     #
#                                                  #
####################################################

# https://www.home-assistant.io/components/speedtestdotnet/

speedtestdotnet:
  server_id: 6601
  monitored_conditions:
    - download
    - upload
    - ping

####################################################
#                                                  #
#                CIRCADIAN LIGHTS                  #
#                                                  #
####################################################

# https://community.home-assistant.io/t/circadian-lighting-custom-component/61246

circadian_lighting:
  min_colortemp: 2000
  max_colortemp: 6500

####################################################
#                                                  #
#                    DARKSKY                       #
#                                                  #
####################################################

# https://www.home-assistant.io/components/weather.darksky/

weather:
  - platform: darksky
    api_key: !secret dsky_api

####################################################
#                                                  #
#                    LUFTDATEN                     #
#                                                  #
####################################################

# https://www.home-assistant.io/components/luftdaten/

luftdaten:
  sensor_id: 19149
  show_on_map: false
  sensors:
    monitored_conditions:
      - P1
      - P2

####################################################
#                                                  #
#                       HACS                       #
#                                                  #
####################################################

# https://custom-components.github.io/hacs/

hacs:
  token: !secret github_token
  options:
    release_limit: 5

####################################################
#                                                  #
#                 MOBILE APP                       #
#                                                  #
####################################################

# https://www.home-assistant.io/integrations/mobile_app/

mobile_app:

####################################################
#                                                  #
#                BROWSER MOD                       #
#                                                  #
####################################################

# https://github.com/thomasloven/hass-browser_mod
# already used in dwanins theme

#browser_mod:

####################################################
#                                                  #
#                   TANKERKOENIG                   #
#                                                  #
####################################################

#https://www.home-assistant.io/integrations/tankerkoenig/

tankerkoenig:
  api_key: !secret tanker_api
  radius: 6
  fuel_types:
    - "e10"

####################################################
#                                                  #
#                     ROBOROCK                     #
#                                                  #
####################################################

#https://www.home-assistant.io/integrations/tankerkoenig/

vacuum:
  - platform: xiaomi_miio
    host: 192.168.178.100
    token: !secret roborock_token

####################################################
#                                                  #
#               TIMESCALE LTSS                     #
#                                                  #
####################################################

# https://github.com/freol35241/ltss

ltss:
    db_url: !secret ltss_url
    include:
        domains:
        - binary_sensor
        - climate
        - light
        - media_player
        - person
        - sensor
        - switch
    exclude:
        entities:
        - sensor.time
        - sensor.time_2
        - sensor.time_date
        - sensor.time_utc
        - sensor.date_time
        - sensor.date_time_iso
        - sensor.internet_time

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################