########################################################
#                                                       #
#        SONOS GERÄTE JEDEN MORGEN ZURÜCKSETZEN         #
#                                                       #
#########################################################

# https://www.home-assistant.io/components/media_player.sonos/

- alias: "Media - Sonos Player jeden Morgen zurücksetzen"
  initial_state: 'on'
  trigger:
    - platform: time
      at: '05:00'
  action:
    - service: sonos.unjoin
      data:
        entity_id:
        - media_player.sonos_bad
        - media_player.sonos_buero
        - media_player.sonos_schlafzimmer
        - media_player.sonos_wohnzimmer
    - service: media_player.clear_playlist
      data:
        entity_id:
        - media_player.sonos_bad
        - media_player.sonos_buero
        - media_player.sonos_schlafzimmer
        - media_player.sonos_wohnzimmer

########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
